version: '3.8'
services:
  bun:
    image: oven/bun@sha256:f885d8ebe5799f61b4a580851d68147eff44c2090a13ff01728a58d42964cad1
    ports:
      - 4455:8080
    volumes:
      -  "./:/home/bun/app"
    # command: /bin/sh -c "bun run --watch ./src/index.ts"
    command: /bin/sh -c "ls -la && pwd && cat README.md && cat docker-compose.yml"
